---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "5"
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      initContainers:
      - name: wait-postgres
        image: alpine:3.6
        command: ['/bin/sh', '-c', 'while ! getent ahostsv4 postgres; do sleep 1; echo -n .; done']
      containers:
        - name: migration
          command: ['/bin/sh', '-c', 'pipenv run python manage.py migrate todo']
          image: {{ .Values.global.image_name }}
          name: migration
          volumeMounts:
          - name: config-volume
            mountPath: /app/gtd/project/local.py
            subPath: local.py
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: django-todo-local-py
  backoffLimit: 2
